


### GET ORGS
GET http://localhost:3030/org 
Content-Type: application/json


### UPDATE ORG
PATCH http://localhost:3030/org/651d126674f9e4e6f18559e9
Content-Type: application/json

{
  "group_a_id": -4066202780,
  "group_b_id": -4066202780
}



### FOODS
GET http://localhost:3030/food
Content-Type: application/json

### FOOD CREATE
POST http://localhost:3030/food
Content-Type: application/json

{
  "name": "Maxito",
  "cost": 15000,
  "category": "drinks",
  "org": "651d126674f9e4e6f18559e9",
  "products": []
}


### FOOD PRODUCTS UPDATE
POST http://localhost:3030/food/products/66149e6dd1f64ff0a94980b0
Content-Type: application/json

{
  "product": "66149e64d1f64ff0a94980ad",
  "amount": 1
}

### FOOD DELETE
DELETE http://localhost:3030/food/6613d719df3d4825e4147456
Content-Type: application/json


### GET PRODUCT
GET http://localhost:3030/product
Content-Type: application/json



### PRODUCT
POST http://localhost:3030/product
Content-Type: application/json

{
  "name": "Maxito",
  "cost": 13000,
  "unit": "dona",
  "org": "651d126674f9e4e6f18559e9",
  "amount": 1
}


### USERS
GET http://localhost:3030/user?search="as"
Content-Type: application/json