
### POST
POST http://localhost:9000/auth/login 
Content-Type: application/json

{
  "phone_number":"+998913650221"
}



### update user
PUT http://localhost:9000/user 
Content-Type: application/json 

{
  "_id":"6505851a044812f315a7e8fe",
  "org":"650012d462949f8744859129"
}


### GET User
GET http://localhost:9000/user 
Content-Type: application/json


### GET Org
GET http://localhost:9000/product 
Content-Type: application/json


### POST
POST http://localhost:9000/settings/otp-info
Content-Type: application/json

{
  "email":"asrorshahobiddinov509@gmail.com",
  "password":"gF5rDbmX8YLP7fcpU6RRZdDeSJzkq3feb8RAwEIV"
}



### Create Product
POST http://localhost:9000/product 
Content-Type: application/json

{
  "name":"",
  "unit":""
}



### Login
POST http://localhost:9000/auth 
Content-Type: application/json

{
  "phone_number":"913650221",
  "password":"12345678"
}





### get product
GET http://localhost:9000/food 
Content-Type: application/json


### Create Prouct
POST http://localhost:9000/product
Content-Type: application/json

{
  "name":"Sneackers",
  "unit":"dona",
  "org":"650001df0394e11e1233e3cb",
  "cost":9000
}



### Create Food
POST http://localhost:9000/food 
Content-Type: application/json 

{
  "name":"Snackers",
  "org":"650001df0394e11e1233e3cb",
  "cost":9000,
  "products": [
    {
      "product":"6500470eaf2c08b6c4628a2b",
      "amount":1
    }
  ],
  "category":"snacks"
}


### Send MEsas
POST  http://localhost:9000/user/send-message 
Content-Type: application/json 

{
  "message":"nima gap Rasul oka"
}



###
POST https://notify.eskiz.uz/api/auth/login

@formData
Content-Disposition: form-data; name="email"

asrorshahobiddinov509@gmail.com

@formData
Content-Disposition: form-data; name="password"
aaa13579A# 



###
POST http://localhost:7000/auth/passanger/send-sms
Content-Type: application/json 

{
  "phone_number":"331145004"
}



### 
POST http://localhost:9000/order
Content-Type: application/json

{
  "client":"64ff00a049490c972a59020",
  "org":"650164a582143bd5e27849eb",
  "foods": [
    {
      "food":"65004729af2c08b6c4628a2e",
      "amount":2
    }
  ]
}


### payment
PATCH http://localhost:9000/user/payment
Content-Type: application/json

{
  "amount": 10000,
  "user": "64ff00bb49490c972a59020c",
  "type": true
}





### login
POST http://localhost:9000/admin/login 
Content-Type: application/json

{
  "phone_number":"913650221",
  "password":"password123"
}



###
POST http://localhost:9000/admin 
Content-Type: application/json 

{
  "phone_number": "909336272",
  "fullname": "Javohir oka",
  "password": "password123",
  "org": "650001df0394e11e1233e3cb",
  "role": "cook"
}


### edit role
PATCH http://localhost:9000/user/role 
Content-Type: application/json

{
  "user":"6505a05e894bb772e4a81006",
  "role":"cook"
}